# -*- coding: utf-8 -*-
"""project 3 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eBLZCXx1zgnmiwQvPtcq7OZ-bq2WHGKR
"""

import numpy as np
import matplotlib.pyplot as plt

x= np.linspace(-5,5,500)

y1 =x**3
y2=np.cos(1.2*x)
y3=np.exp(-x**2)

plt.title('plot of x^3')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.plot(x,y1,'--')
#  posetive point
plt.fill_between(x,y1,color='turquoise',alpha=1)
plt.show()

plt.title('plot of mathemathical functions')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.plot(x,y2,'g--',label='y2=1.2x')
plt.plot(x,y3,'r',label='y3=e ^ (-x)^2')
plt.legend()
plt.grid(True)
plt.show()