# -*- coding: utf-8 -*-
"""project 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AlcRwRDruz3iPszy5qvKSUWYA3mJNfkg
"""

import numpy as np
import matplotlib.pyplot as plt

def plot_normal_dist(n, mean=0, std=1):
    data = np.random.normal(mean, std, n)
    plt.hist(data, bins=100)
    plt.title('normal distribution')

    plt.xlabel('value')
    plt.ylabel('frequency')
    plt.grid(True)
    plt.show()

plot_normal_dist(10)

plot_normal_dist(1000)

plot_normal_dist(100000)