# -*- coding: utf-8 -*-
"""code_melli.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15l5NTqYkFaGYhfG6C9hfsBun0cg82TD0
"""

import numpy as np

code = input('Enter your national ID: ')

print(code)

if len(code) > 10 or len(code) < 8:
    print('Invalid')
else:
    # Add zeros to the start of the code to become 10 digits
    code = code.zfill(10)
    print(code)

if len(set(code)) == 1:
    print('Invalid')

code_array = np.array(list(code), dtype=int)[:-1]
code_array

place_array = np.arange(2, 11)[::-1]
place_array

checksum = np.dot(code_array, place_array)
# checksum = code_array @ place_array
checksum

remainder = checksum % 11
remainder

if remainder < 2:
    control_digit = remainder
else:
    control_digit = 11 - remainder
control_digit

if control_digit == int(code[-1]):
    print('Valid')
else:
    print('Invalid')

